# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Clock_Timer_Alarm_msg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Clock_Timer_msg(object):
    def setupUi(self, Clock_Timer_msg):
        Clock_Timer_msg.setObjectName("Clock_Timer_msg")
        Clock_Timer_msg.resize(543, 299)
        Clock_Timer_msg.setMinimumSize(QtCore.QSize(543, 299))
        Clock_Timer_msg.setMaximumSize(QtCore.QSize(728, 499))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/warning.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Clock_Timer_msg.setWindowIcon(icon)
        Clock_Timer_msg.setSizeGripEnabled(False)
        Clock_Timer_msg.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(Clock_Timer_msg)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit_msg = QtWidgets.QTextEdit(Clock_Timer_msg)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_msg.setFont(font)
        self.textEdit_msg.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.textEdit_msg.setReadOnly(True)
        self.textEdit_msg.setObjectName("textEdit_msg")
        self.gridLayout.addWidget(self.textEdit_msg, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.pushB_exit = QtWidgets.QPushButton(Clock_Timer_msg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushB_exit.sizePolicy().hasHeightForWidth())
        self.pushB_exit.setSizePolicy(sizePolicy)
        self.pushB_exit.setMinimumSize(QtCore.QSize(86, 46))
        self.pushB_exit.setMaximumSize(QtCore.QSize(86, 46))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushB_exit.setFont(font)
        self.pushB_exit.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.pushB_exit.setObjectName("pushB_exit")
        self.horizontalLayout_5.addWidget(self.pushB_exit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)

        self.retranslateUi(Clock_Timer_msg)
        QtCore.QMetaObject.connectSlotsByName(Clock_Timer_msg)

    def retranslateUi(self, Clock_Timer_msg):
        _translate = QtCore.QCoreApplication.translate
        Clock_Timer_msg.setWindowTitle(_translate("Clock_Timer_msg", "Сообщение"))
        self.textEdit_msg.setHtml(_translate("Clock_Timer_msg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushB_exit.setText(_translate("Clock_Timer_msg", "Выход"))
import Clock_new_p_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Clock_Timer_msg = QtWidgets.QDialog()
    ui = Ui_Clock_Timer_msg()
    ui.setupUi(Clock_Timer_msg)
    Clock_Timer_msg.show()
    sys.exit(app.exec_())
