# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Clock_Timer_Sound_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Clock_Timer_Sound(object):
    def setupUi(self, Clock_Timer_Sound):
        Clock_Timer_Sound.setObjectName("Clock_Timer_Sound")
        Clock_Timer_Sound.resize(544, 119)
        Clock_Timer_Sound.setMinimumSize(QtCore.QSize(482, 96))
        Clock_Timer_Sound.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/music_22279.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Clock_Timer_Sound.setWindowIcon(icon)
        Clock_Timer_Sound.setSizeGripEnabled(False)
        Clock_Timer_Sound.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(Clock_Timer_Sound)
        self.gridLayout.setObjectName("gridLayout")
        self.label_sound = QtWidgets.QLabel(Clock_Timer_Sound)
        self.label_sound.setMinimumSize(QtCore.QSize(413, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_sound.setFont(font)
        self.label_sound.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.label_sound.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sound.setWordWrap(True)
        self.label_sound.setObjectName("label_sound")
        self.gridLayout.addWidget(self.label_sound, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushB_start_pause = QtWidgets.QPushButton(Clock_Timer_Sound)
        self.pushB_start_pause.setMinimumSize(QtCore.QSize(150, 40))
        self.pushB_start_pause.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushB_start_pause.setFont(font)
        self.pushB_start_pause.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.pushB_start_pause.setObjectName("pushB_start_pause")
        self.horizontalLayout.addWidget(self.pushB_start_pause)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushB_stop = QtWidgets.QPushButton(Clock_Timer_Sound)
        self.pushB_stop.setMinimumSize(QtCore.QSize(150, 40))
        self.pushB_stop.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushB_stop.setFont(font)
        self.pushB_stop.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.pushB_stop.setObjectName("pushB_stop")
        self.horizontalLayout.addWidget(self.pushB_stop)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(Clock_Timer_Sound)
        QtCore.QMetaObject.connectSlotsByName(Clock_Timer_Sound)

    def retranslateUi(self, Clock_Timer_Sound):
        _translate = QtCore.QCoreApplication.translate
        Clock_Timer_Sound.setWindowTitle(_translate("Clock_Timer_Sound", "Проверка звучания"))
        self.label_sound.setText(_translate("Clock_Timer_Sound", "TextLabel"))
        self.pushB_start_pause.setText(_translate("Clock_Timer_Sound", "Старт"))
        self.pushB_stop.setText(_translate("Clock_Timer_Sound", "Стоп"))
import Clock_new_p_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Clock_Timer_Sound = QtWidgets.QDialog()
    ui = Ui_Clock_Timer_Sound()
    ui.setupUi(Clock_Timer_Sound)
    Clock_Timer_Sound.show()
    sys.exit(app.exec_())
